[package]
name = "maki"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { version = "0.6.0", features = ["parallel", "zeroize"] }
base64ct = { version = "1.8.3", features = ["alloc"] }
chacha20poly1305 = { version = "0.11.0", features = ["zeroize"] }
crossterm = "0.29.0"
getrandom = "0.4.3"
image = { version = "0.25.10", default-features = false, features = ["webp"] }
ratatui = "0.30.2"
zeroize = "1.9.0"
